name = "PolynomialsMutableArithmetics"
uuid = "79a39cca-baf0-44da-ad00-3ac4adec8886"
authors = ["jverzani <jverzani@gmail.com> based on code contributed by Benoît Legat"]
version = "1.0.0"

[deps]
MutableArithmetics = "d8a4904e-b15c-11e9-3269-09a3773c0cb0"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
julia = "1.6"
MutableArithmetics = "1"
Polynomials = "3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
